#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <LMErr.h>

#include "WinError.itc.h"
#include "LMErr.itc.h"

namespace itc {

const Enum2Val_st _e2v_NERR_xxx[] =
{
	ITC_NAMEPAIR(NERR_NetNotStarted), // NERR_BASE+2
	ITC_NAMEPAIR(NERR_UnknownServer), // NERR_BASE+3
	ITC_NAMEPAIR(NERR_ShareMem), // NERR_BASE+4
	ITC_NAMEPAIR(NERR_NoNetworkResource), // NERR_BASE+5
	ITC_NAMEPAIR(NERR_RemoteOnly), // NERR_BASE+6
	ITC_NAMEPAIR(NERR_DevNotRedirected), // NERR_BASE+7
	ITC_NAMEPAIR(NERR_ServerNotStarted), // NERR_BASE+14
	ITC_NAMEPAIR(NERR_ItemNotFound), // NERR_BASE+15
	ITC_NAMEPAIR(NERR_UnknownDevDir), // NERR_BASE+16
	ITC_NAMEPAIR(NERR_RedirectedPath), // NERR_BASE+17
	ITC_NAMEPAIR(NERR_DuplicateShare), // NERR_BASE+18
	ITC_NAMEPAIR(NERR_NoRoom), // NERR_BASE+19
	ITC_NAMEPAIR(NERR_TooManyItems), // NERR_BASE+21
	ITC_NAMEPAIR(NERR_InvalidMaxUsers), // NERR_BASE+22
	ITC_NAMEPAIR(NERR_BufTooSmall), // NERR_BASE+23
	ITC_NAMEPAIR(NERR_RemoteErr), // NERR_BASE+27
	ITC_NAMEPAIR(NERR_LanmanIniError), // NERR_BASE+31
	ITC_NAMEPAIR(NERR_NetworkError), // NERR_BASE+36
	ITC_NAMEPAIR(NERR_WkstaInconsistentState), // NERR_BASE+37
	ITC_NAMEPAIR(NERR_WkstaNotStarted), // NERR_BASE+38
	ITC_NAMEPAIR(NERR_BrowserNotStarted), // NERR_BASE+39
	ITC_NAMEPAIR(NERR_InternalError), // NERR_BASE+40
	ITC_NAMEPAIR(NERR_BadTransactConfig), // NERR_BASE+41
	ITC_NAMEPAIR(NERR_InvalidAPI), // NERR_BASE+42
	ITC_NAMEPAIR(NERR_BadEventName), // NERR_BASE+43
	ITC_NAMEPAIR(NERR_DupNameReboot), // NERR_BASE+44
	ITC_NAMEPAIR(NERR_CfgCompNotFound), // NERR_BASE+46
	ITC_NAMEPAIR(NERR_CfgParamNotFound), // NERR_BASE+47
	ITC_NAMEPAIR(NERR_LineTooLong), // NERR_BASE+49
	ITC_NAMEPAIR(NERR_QNotFound), // NERR_BASE+50
	ITC_NAMEPAIR(NERR_JobNotFound), // NERR_BASE+51
	ITC_NAMEPAIR(NERR_DestNotFound), // NERR_BASE+52
	ITC_NAMEPAIR(NERR_DestExists), // NERR_BASE+53
	ITC_NAMEPAIR(NERR_QExists), // NERR_BASE+54
	ITC_NAMEPAIR(NERR_QNoRoom), // NERR_BASE+55
	ITC_NAMEPAIR(NERR_JobNoRoom), // NERR_BASE+56
	ITC_NAMEPAIR(NERR_DestNoRoom), // NERR_BASE+57
	ITC_NAMEPAIR(NERR_DestIdle), // NERR_BASE+58
	ITC_NAMEPAIR(NERR_DestInvalidOp), // NERR_BASE+59
	ITC_NAMEPAIR(NERR_ProcNoRespond), // NERR_BASE+60
	ITC_NAMEPAIR(NERR_SpoolerNotLoaded), // NERR_BASE+61
	ITC_NAMEPAIR(NERR_DestInvalidState), // NERR_BASE+62
	ITC_NAMEPAIR(NERR_QInvalidState), // NERR_BASE+63
	ITC_NAMEPAIR(NERR_JobInvalidState), // NERR_BASE+64
	ITC_NAMEPAIR(NERR_SpoolNoMemory), // NERR_BASE+65
	ITC_NAMEPAIR(NERR_DriverNotFound), // NERR_BASE+66
	ITC_NAMEPAIR(NERR_DataTypeInvalid), // NERR_BASE+67
	ITC_NAMEPAIR(NERR_ProcNotFound), // NERR_BASE+68
	ITC_NAMEPAIR(NERR_ServiceTableLocked), // NERR_BASE+80
	ITC_NAMEPAIR(NERR_ServiceTableFull), // NERR_BASE+81
	ITC_NAMEPAIR(NERR_ServiceInstalled), // NERR_BASE+82
	ITC_NAMEPAIR(NERR_ServiceEntryLocked), // NERR_BASE+83
	ITC_NAMEPAIR(NERR_ServiceNotInstalled), // NERR_BASE+84
	ITC_NAMEPAIR(NERR_BadServiceName), // NERR_BASE+85
	ITC_NAMEPAIR(NERR_ServiceCtlTimeout), // NERR_BASE+86
	ITC_NAMEPAIR(NERR_ServiceCtlBusy), // NERR_BASE+87
	ITC_NAMEPAIR(NERR_BadServiceProgName), // NERR_BASE+88
	ITC_NAMEPAIR(NERR_ServiceNotCtrl), // NERR_BASE+89
	ITC_NAMEPAIR(NERR_ServiceKillProc), // NERR_BASE+90
	ITC_NAMEPAIR(NERR_ServiceCtlNotValid), // NERR_BASE+91
	ITC_NAMEPAIR(NERR_NotInDispatchTbl), // NERR_BASE+92
	ITC_NAMEPAIR(NERR_BadControlRecv), // NERR_BASE+93
	ITC_NAMEPAIR(NERR_ServiceNotStarting), // NERR_BASE+94
	ITC_NAMEPAIR(NERR_AlreadyLoggedOn), // NERR_BASE+100
	ITC_NAMEPAIR(NERR_NotLoggedOn), // NERR_BASE+101
	ITC_NAMEPAIR(NERR_BadUsername), // NERR_BASE+102
	ITC_NAMEPAIR(NERR_BadPassword), // NERR_BASE+103
	ITC_NAMEPAIR(NERR_UnableToAddName_W), // NERR_BASE+104
	ITC_NAMEPAIR(NERR_UnableToAddName_F), // NERR_BASE+105
	ITC_NAMEPAIR(NERR_UnableToDelName_W), // NERR_BASE+106
	ITC_NAMEPAIR(NERR_UnableToDelName_F), // NERR_BASE+107
	ITC_NAMEPAIR(NERR_LogonsPaused), // NERR_BASE+109
	ITC_NAMEPAIR(NERR_LogonServerConflict), // NERR_BASE+110
	ITC_NAMEPAIR(NERR_LogonNoUserPath), // NERR_BASE+111
	ITC_NAMEPAIR(NERR_LogonScriptError), // NERR_BASE+112
	ITC_NAMEPAIR(NERR_StandaloneLogon), // NERR_BASE+114
	ITC_NAMEPAIR(NERR_LogonServerNotFound), // NERR_BASE+115
	ITC_NAMEPAIR(NERR_LogonDomainExists), // NERR_BASE+116
	ITC_NAMEPAIR(NERR_NonValidatedLogon), // NERR_BASE+117
	ITC_NAMEPAIR(NERR_ACFNotFound), // NERR_BASE+119
	ITC_NAMEPAIR(NERR_GroupNotFound), // NERR_BASE+120
	ITC_NAMEPAIR(NERR_UserNotFound), // NERR_BASE+121
	ITC_NAMEPAIR(NERR_ResourceNotFound), // NERR_BASE+122
	ITC_NAMEPAIR(NERR_GroupExists), // NERR_BASE+123
	ITC_NAMEPAIR(NERR_UserExists), // NERR_BASE+124
	ITC_NAMEPAIR(NERR_ResourceExists), // NERR_BASE+125
	ITC_NAMEPAIR(NERR_NotPrimary), // NERR_BASE+126
	ITC_NAMEPAIR(NERR_ACFNotLoaded), // NERR_BASE+127
	ITC_NAMEPAIR(NERR_ACFNoRoom), // NERR_BASE+128
	ITC_NAMEPAIR(NERR_ACFFileIOFail), // NERR_BASE+129
	ITC_NAMEPAIR(NERR_ACFTooManyLists), // NERR_BASE+130
	ITC_NAMEPAIR(NERR_UserLogon), // NERR_BASE+131
	ITC_NAMEPAIR(NERR_ACFNoParent), // NERR_BASE+132
	ITC_NAMEPAIR(NERR_CanNotGrowSegment), // NERR_BASE+133
	ITC_NAMEPAIR(NERR_SpeGroupOp), // NERR_BASE+134
	ITC_NAMEPAIR(NERR_NotInCache), // NERR_BASE+135
	ITC_NAMEPAIR(NERR_UserInGroup), // NERR_BASE+136
	ITC_NAMEPAIR(NERR_UserNotInGroup), // NERR_BASE+137
	ITC_NAMEPAIR(NERR_AccountUndefined), // NERR_BASE+138
	ITC_NAMEPAIR(NERR_AccountExpired), // NERR_BASE+139
	ITC_NAMEPAIR(NERR_InvalidWorkstation), // NERR_BASE+140
	ITC_NAMEPAIR(NERR_InvalidLogonHours), // NERR_BASE+141
	ITC_NAMEPAIR(NERR_PasswordExpired), // NERR_BASE+142
	ITC_NAMEPAIR(NERR_PasswordCantChange), // NERR_BASE+143
	ITC_NAMEPAIR(NERR_PasswordHistConflict), // NERR_BASE+144
	ITC_NAMEPAIR(NERR_PasswordTooShort), // NERR_BASE+145
	ITC_NAMEPAIR(NERR_PasswordTooRecent), // NERR_BASE+146
	ITC_NAMEPAIR(NERR_InvalidDatabase), // NERR_BASE+147
	ITC_NAMEPAIR(NERR_DatabaseUpToDate), // NERR_BASE+148
	ITC_NAMEPAIR(NERR_SyncRequired), // NERR_BASE+149
	ITC_NAMEPAIR(NERR_UseNotFound), // NERR_BASE+150
	ITC_NAMEPAIR(NERR_BadAsgType), // NERR_BASE+151
	ITC_NAMEPAIR(NERR_DeviceIsShared), // NERR_BASE+152
	ITC_NAMEPAIR(NERR_SameAsComputerName), // NERR_BASE+153
	ITC_NAMEPAIR(NERR_NoComputerName), // NERR_BASE+170
	ITC_NAMEPAIR(NERR_MsgAlreadyStarted), // NERR_BASE+171
	ITC_NAMEPAIR(NERR_MsgInitFailed), // NERR_BASE+172
	ITC_NAMEPAIR(NERR_NameNotFound), // NERR_BASE+173
	ITC_NAMEPAIR(NERR_AlreadyForwarded), // NERR_BASE+174
	ITC_NAMEPAIR(NERR_AddForwarded), // NERR_BASE+175
	ITC_NAMEPAIR(NERR_AlreadyExists), // NERR_BASE+176
	ITC_NAMEPAIR(NERR_TooManyNames), // NERR_BASE+177
	ITC_NAMEPAIR(NERR_DelComputerName), // NERR_BASE+178
	ITC_NAMEPAIR(NERR_LocalForward), // NERR_BASE+179
	ITC_NAMEPAIR(NERR_GrpMsgProcessor), // NERR_BASE+180
	ITC_NAMEPAIR(NERR_PausedRemote), // NERR_BASE+181
	ITC_NAMEPAIR(NERR_BadReceive), // NERR_BASE+182
	ITC_NAMEPAIR(NERR_NameInUse), // NERR_BASE+183
	ITC_NAMEPAIR(NERR_MsgNotStarted), // NERR_BASE+184
	ITC_NAMEPAIR(NERR_NotLocalName), // NERR_BASE+185
	ITC_NAMEPAIR(NERR_NoForwardName), // NERR_BASE+186
	ITC_NAMEPAIR(NERR_RemoteFull), // NERR_BASE+187
	ITC_NAMEPAIR(NERR_NameNotForwarded), // NERR_BASE+188
	ITC_NAMEPAIR(NERR_TruncatedBroadcast), // NERR_BASE+189
	ITC_NAMEPAIR(NERR_InvalidDevice), // NERR_BASE+194
	ITC_NAMEPAIR(NERR_WriteFault), // NERR_BASE+195
	ITC_NAMEPAIR(NERR_DuplicateName), // NERR_BASE+197
	ITC_NAMEPAIR(NERR_DeleteLater), // NERR_BASE+198
	ITC_NAMEPAIR(NERR_IncompleteDel), // NERR_BASE+199
	ITC_NAMEPAIR(NERR_MultipleNets), // NERR_BASE+200
	ITC_NAMEPAIR(NERR_NetNameNotFound), // NERR_BASE+210
	ITC_NAMEPAIR(NERR_DeviceNotShared), // NERR_BASE+211
	ITC_NAMEPAIR(NERR_ClientNameNotFound), // NERR_BASE+212
	ITC_NAMEPAIR(NERR_FileIdNotFound), // NERR_BASE+214
	ITC_NAMEPAIR(NERR_ExecFailure), // NERR_BASE+215
	ITC_NAMEPAIR(NERR_TmpFile), // NERR_BASE+216
	ITC_NAMEPAIR(NERR_TooMuchData), // NERR_BASE+217
	ITC_NAMEPAIR(NERR_DeviceShareConflict), // NERR_BASE+218
	ITC_NAMEPAIR(NERR_BrowserTableIncomplete), // NERR_BASE+219
	ITC_NAMEPAIR(NERR_NotLocalDomain), // NERR_BASE+220
	ITC_NAMEPAIR(NERR_IsDfsShare), // NERR_BASE+221
	ITC_NAMEPAIR(NERR_DevInvalidOpCode), // NERR_BASE+231
	ITC_NAMEPAIR(NERR_DevNotFound), // NERR_BASE+232
	ITC_NAMEPAIR(NERR_DevNotOpen), // NERR_BASE+233
	ITC_NAMEPAIR(NERR_BadQueueDevString), // NERR_BASE+234
	ITC_NAMEPAIR(NERR_BadQueuePriority), // NERR_BASE+235
	ITC_NAMEPAIR(NERR_NoCommDevs), // NERR_BASE+237
	ITC_NAMEPAIR(NERR_QueueNotFound), // NERR_BASE+238
	ITC_NAMEPAIR(NERR_BadDevString), // NERR_BASE+240
	ITC_NAMEPAIR(NERR_BadDev), // NERR_BASE+241
	ITC_NAMEPAIR(NERR_InUseBySpooler), // NERR_BASE+242
	ITC_NAMEPAIR(NERR_CommDevInUse), // NERR_BASE+243
	ITC_NAMEPAIR(NERR_InvalidComputer), // NERR_BASE+251
	ITC_NAMEPAIR(NERR_MaxLenExceeded), // NERR_BASE+254
	ITC_NAMEPAIR(NERR_BadComponent), // NERR_BASE+256
	ITC_NAMEPAIR(NERR_CantType), // NERR_BASE+257
	ITC_NAMEPAIR(NERR_TooManyEntries), // NERR_BASE+262
	ITC_NAMEPAIR(NERR_ProfileFileTooBig), // NERR_BASE+270
	ITC_NAMEPAIR(NERR_ProfileOffset), // NERR_BASE+271
	ITC_NAMEPAIR(NERR_ProfileCleanup), // NERR_BASE+272
	ITC_NAMEPAIR(NERR_ProfileUnknownCmd), // NERR_BASE+273
	ITC_NAMEPAIR(NERR_ProfileLoadErr), // NERR_BASE+274
	ITC_NAMEPAIR(NERR_ProfileSaveErr), // NERR_BASE+275
	ITC_NAMEPAIR(NERR_LogOverflow), // NERR_BASE+277
	ITC_NAMEPAIR(NERR_LogFileChanged), // NERR_BASE+278
	ITC_NAMEPAIR(NERR_LogFileCorrupt), // NERR_BASE+279
	ITC_NAMEPAIR(NERR_SourceIsDir), // NERR_BASE+280
	ITC_NAMEPAIR(NERR_BadSource), // NERR_BASE+281
	ITC_NAMEPAIR(NERR_BadDest), // NERR_BASE+282
	ITC_NAMEPAIR(NERR_DifferentServers), // NERR_BASE+283
	ITC_NAMEPAIR(NERR_RunSrvPaused), // NERR_BASE+285
	ITC_NAMEPAIR(NERR_ErrCommRunSrv), // NERR_BASE+289
	ITC_NAMEPAIR(NERR_ErrorExecingGhost), // NERR_BASE+291
	ITC_NAMEPAIR(NERR_ShareNotFound), // NERR_BASE+292
	ITC_NAMEPAIR(NERR_InvalidLana), // NERR_BASE+300
	ITC_NAMEPAIR(NERR_OpenFiles), // NERR_BASE+301
	ITC_NAMEPAIR(NERR_ActiveConns), // NERR_BASE+302
	ITC_NAMEPAIR(NERR_BadPasswordCore), // NERR_BASE+303
	ITC_NAMEPAIR(NERR_DevInUse), // NERR_BASE+304
	ITC_NAMEPAIR(NERR_LocalDrive), // NERR_BASE+305
	ITC_NAMEPAIR(NERR_AlertExists), // NERR_BASE+330
	ITC_NAMEPAIR(NERR_TooManyAlerts), // NERR_BASE+331
	ITC_NAMEPAIR(NERR_NoSuchAlert), // NERR_BASE+332
	ITC_NAMEPAIR(NERR_BadRecipient), // NERR_BASE+333
	ITC_NAMEPAIR(NERR_AcctLimitExceeded), // NERR_BASE+334
	ITC_NAMEPAIR(NERR_InvalidLogSeek), // NERR_BASE+340
	ITC_NAMEPAIR(NERR_BadUasConfig), // NERR_BASE+350
	ITC_NAMEPAIR(NERR_InvalidUASOp), // NERR_BASE+351
	ITC_NAMEPAIR(NERR_LastAdmin), // NERR_BASE+352
	ITC_NAMEPAIR(NERR_DCNotFound), // NERR_BASE+353
	ITC_NAMEPAIR(NERR_LogonTrackingError), // NERR_BASE+354
	ITC_NAMEPAIR(NERR_NetlogonNotStarted), // NERR_BASE+355
	ITC_NAMEPAIR(NERR_CanNotGrowUASFile), // NERR_BASE+356
	ITC_NAMEPAIR(NERR_TimeDiffAtDC), // NERR_BASE+357
	ITC_NAMEPAIR(NERR_PasswordMismatch), // NERR_BASE+358
	ITC_NAMEPAIR(NERR_NoSuchServer), // NERR_BASE+360
	ITC_NAMEPAIR(NERR_NoSuchSession), // NERR_BASE+361
	ITC_NAMEPAIR(NERR_NoSuchConnection), // NERR_BASE+362
	ITC_NAMEPAIR(NERR_TooManyServers), // NERR_BASE+363
	ITC_NAMEPAIR(NERR_TooManySessions), // NERR_BASE+364
	ITC_NAMEPAIR(NERR_TooManyConnections), // NERR_BASE+365
	ITC_NAMEPAIR(NERR_TooManyFiles), // NERR_BASE+366
	ITC_NAMEPAIR(NERR_NoAlternateServers), // NERR_BASE+367
	ITC_NAMEPAIR(NERR_TryDownLevel), // NERR_BASE+370
	ITC_NAMEPAIR(NERR_UPSDriverNotStarted), // NERR_BASE+380
	ITC_NAMEPAIR(NERR_UPSInvalidConfig), // NERR_BASE+381
	ITC_NAMEPAIR(NERR_UPSInvalidCommPort), // NERR_BASE+382
	ITC_NAMEPAIR(NERR_UPSSignalAsserted), // NERR_BASE+383
	ITC_NAMEPAIR(NERR_UPSShutdownFailed), // NERR_BASE+384
	ITC_NAMEPAIR(NERR_BadDosRetCode), // NERR_BASE+400
	ITC_NAMEPAIR(NERR_ProgNeedsExtraMem), // NERR_BASE+401
	ITC_NAMEPAIR(NERR_BadDosFunction), // NERR_BASE+402
	ITC_NAMEPAIR(NERR_RemoteBootFailed), // NERR_BASE+403
	ITC_NAMEPAIR(NERR_BadFileCheckSum), // NERR_BASE+404
	ITC_NAMEPAIR(NERR_NoRplBootSystem), // NERR_BASE+405
	ITC_NAMEPAIR(NERR_RplLoadrNetBiosErr), // NERR_BASE+406
	ITC_NAMEPAIR(NERR_RplLoadrDiskErr), // NERR_BASE+407
	ITC_NAMEPAIR(NERR_ImageParamErr), // NERR_BASE+408
	ITC_NAMEPAIR(NERR_TooManyImageParams), // NERR_BASE+409
	ITC_NAMEPAIR(NERR_NonDosFloppyUsed), // NERR_BASE+410
	ITC_NAMEPAIR(NERR_RplBootRestart), // NERR_BASE+411
	ITC_NAMEPAIR(NERR_RplSrvrCallFailed), // NERR_BASE+412
	ITC_NAMEPAIR(NERR_CantConnectRplSrvr), // NERR_BASE+413
	ITC_NAMEPAIR(NERR_CantOpenImageFile), // NERR_BASE+414
	ITC_NAMEPAIR(NERR_CallingRplSrvr), // NERR_BASE+415
	ITC_NAMEPAIR(NERR_StartingRplBoot), // NERR_BASE+416
	ITC_NAMEPAIR(NERR_RplBootServiceTerm), // NERR_BASE+417
	ITC_NAMEPAIR(NERR_RplBootStartFailed), // NERR_BASE+418
	ITC_NAMEPAIR(NERR_RPL_CONNECTED), // NERR_BASE+419
	ITC_NAMEPAIR(NERR_BrowserConfiguredToNotRun), // NERR_BASE+450
	ITC_NAMEPAIR(NERR_RplNoAdaptersStarted), // NERR_BASE+510
	ITC_NAMEPAIR(NERR_RplBadRegistry), // NERR_BASE+511
	ITC_NAMEPAIR(NERR_RplBadDatabase), // NERR_BASE+512
	ITC_NAMEPAIR(NERR_RplRplfilesShare), // NERR_BASE+513
	ITC_NAMEPAIR(NERR_RplNotRplServer), // NERR_BASE+514
	ITC_NAMEPAIR(NERR_RplCannotEnum), // NERR_BASE+515
	ITC_NAMEPAIR(NERR_RplWkstaInfoCorrupted), // NERR_BASE+516
	ITC_NAMEPAIR(NERR_RplWkstaNotFound), // NERR_BASE+517
	ITC_NAMEPAIR(NERR_RplWkstaNameUnavailable), // NERR_BASE+518
	ITC_NAMEPAIR(NERR_RplProfileInfoCorrupted), // NERR_BASE+519
	ITC_NAMEPAIR(NERR_RplProfileNotFound), // NERR_BASE+520
	ITC_NAMEPAIR(NERR_RplProfileNameUnavailable), // NERR_BASE+521
	ITC_NAMEPAIR(NERR_RplProfileNotEmpty), // NERR_BASE+522
	ITC_NAMEPAIR(NERR_RplConfigInfoCorrupted), // NERR_BASE+523
	ITC_NAMEPAIR(NERR_RplConfigNotFound), // NERR_BASE+524
	ITC_NAMEPAIR(NERR_RplAdapterInfoCorrupted), // NERR_BASE+525
	ITC_NAMEPAIR(NERR_RplInternal), // NERR_BASE+526
	ITC_NAMEPAIR(NERR_RplVendorInfoCorrupted), // NERR_BASE+527
	ITC_NAMEPAIR(NERR_RplBootInfoCorrupted), // NERR_BASE+528
	ITC_NAMEPAIR(NERR_RplWkstaNeedsUserAcct), // NERR_BASE+529
	ITC_NAMEPAIR(NERR_RplNeedsRPLUSERAcct), // NERR_BASE+530
	ITC_NAMEPAIR(NERR_RplBootNotFound), // NERR_BASE+531
	ITC_NAMEPAIR(NERR_RplIncompatibleProfile), // NERR_BASE+532
	ITC_NAMEPAIR(NERR_RplAdapterNameUnavailable), // NERR_BASE+533
	ITC_NAMEPAIR(NERR_RplConfigNotEmpty), // NERR_BASE+534
	ITC_NAMEPAIR(NERR_RplBootInUse), // NERR_BASE+535
	ITC_NAMEPAIR(NERR_RplBackupDatabase), // NERR_BASE+536
	ITC_NAMEPAIR(NERR_RplAdapterNotFound), // NERR_BASE+537
	ITC_NAMEPAIR(NERR_RplVendorNotFound), // NERR_BASE+538
	ITC_NAMEPAIR(NERR_RplVendorNameUnavailable), // NERR_BASE+539
	ITC_NAMEPAIR(NERR_RplBootNameUnavailable), // NERR_BASE+540
	ITC_NAMEPAIR(NERR_RplConfigNameUnavailable), // NERR_BASE+541
	ITC_NAMEPAIR(NERR_DfsInternalCorruption), // NERR_BASE+560
	ITC_NAMEPAIR(NERR_DfsVolumeDataCorrupt), // NERR_BASE+561
	ITC_NAMEPAIR(NERR_DfsNoSuchVolume), // NERR_BASE+562
	ITC_NAMEPAIR(NERR_DfsVolumeAlreadyExists), // NERR_BASE+563
	ITC_NAMEPAIR(NERR_DfsAlreadyShared), // NERR_BASE+564
	ITC_NAMEPAIR(NERR_DfsNoSuchShare), // NERR_BASE+565
	ITC_NAMEPAIR(NERR_DfsNotALeafVolume), // NERR_BASE+566
	ITC_NAMEPAIR(NERR_DfsLeafVolume), // NERR_BASE+567
	ITC_NAMEPAIR(NERR_DfsVolumeHasMultipleServers), // NERR_BASE+568
	ITC_NAMEPAIR(NERR_DfsCantCreateJunctionPoint), // NERR_BASE+569
	ITC_NAMEPAIR(NERR_DfsServerNotDfsAware), // NERR_BASE+570
	ITC_NAMEPAIR(NERR_DfsBadRenamePath), // NERR_BASE+571
	ITC_NAMEPAIR(NERR_DfsVolumeIsOffline), // NERR_BASE+572
	ITC_NAMEPAIR(NERR_DfsNoSuchServer), // NERR_BASE+573
	ITC_NAMEPAIR(NERR_DfsCyclicalName), // NERR_BASE+574
	ITC_NAMEPAIR(NERR_DfsNotSupportedInServerDfs), // NERR_BASE+575
	ITC_NAMEPAIR(NERR_DfsDuplicateService), // NERR_BASE+576
	ITC_NAMEPAIR(NERR_DfsCantRemoveLastServerShare), // NERR_BASE+577
	ITC_NAMEPAIR(NERR_DfsVolumeIsInterDfs), // NERR_BASE+578
	ITC_NAMEPAIR(NERR_DfsInconsistent), // NERR_BASE+579
	ITC_NAMEPAIR(NERR_DfsServerUpgraded), // NERR_BASE+580
	ITC_NAMEPAIR(NERR_DfsDataIsIdentical), // NERR_BASE+581
	ITC_NAMEPAIR(NERR_DfsCantRemoveDfsRoot), // NERR_BASE+582
	ITC_NAMEPAIR(NERR_DfsChildOrParentInDfs), // NERR_BASE+583
	ITC_NAMEPAIR(NERR_DfsInternalError), // NERR_BASE+590
	ITC_NAMEPAIR(NERR_SetupAlreadyJoined), // NERR_BASE+591
	ITC_NAMEPAIR(NERR_SetupNotJoined), // NERR_BASE+592
	ITC_NAMEPAIR(NERR_SetupDomainController), // NERR_BASE+593
	ITC_NAMEPAIR(NERR_DefaultJoinRequired), // NERR_BASE+594
	ITC_NAMEPAIR(NERR_InvalidWorkgroupName), // NERR_BASE+595
	ITC_NAMEPAIR(NERR_NameUsesIncompatibleCodePage), // NERR_BASE+596
	ITC_NAMEPAIR(NERR_ComputerAccountNotFound), // NERR_BASE+597
	ITC_NAMEPAIR(NERR_PersonalSku), // NERR_BASE+598
	ITC_NAMEPAIR(NERR_SetupCheckDNSConfig), // NERR_BASE+599
	ITC_NAMEPAIR(NERR_PasswordMustChange), // NERR_BASE + 601
	ITC_NAMEPAIR(NERR_AccountLockedOut), // NERR_BASE + 602
	ITC_NAMEPAIR(NERR_PasswordTooLong), // NERR_BASE + 603
	ITC_NAMEPAIR(NERR_PasswordNotComplexEnough), // NERR_BASE + 604
	ITC_NAMEPAIR(NERR_PasswordFilterError), // NERR_BASE + 605
	ITC_NAMEPAIR(NERR_NoOfflineJoinInfo), // NERR_BASE + 609
	ITC_NAMEPAIR(NERR_BadOfflineJoinInfo), // NERR_BASE + 610
	ITC_NAMEPAIR(NERR_CantCreateJoinInfo), // NERR_BASE + 611
	ITC_NAMEPAIR(NERR_BadDomainJoinInfo), // NERR_BASE + 612
	ITC_NAMEPAIR(NERR_JoinPerformedMustRestart), // NERR_BASE + 613
	ITC_NAMEPAIR(NERR_NoJoinPending), // NERR_BASE + 614
	ITC_NAMEPAIR(NERR_ValuesNotSet), // NERR_BASE + 615
	ITC_NAMEPAIR(NERR_CantVerifyHostname), // NERR_BASE + 616
	ITC_NAMEPAIR(NERR_CantLoadOfflineHive), // NERR_BASE + 617
	ITC_NAMEPAIR(NERR_ConnectionInsecure), // NERR_BASE + 618
	ITC_NAMEPAIR(NERR_ProvisioningBlobUnsupported), // NERR_BASE + 619
};
CInterpretConst NERR_xxx(
	new Enum2Val_merge(
		_e2v_NERR_xxx, ARRAYSIZE(_e2v_NERR_xxx),
		_e2v_WinError, N_e2v_WinError,
		nullptr, 0) // this Enum2Val_merge object will not be deleted, by design
	, ITCF_SINT
	);

} //namespace itc
