#ifndef __itc__mmsystem_h_
#define __itc__mmsystem_h_
#define __itc__mmsystem_h_created_ 20260624
#define __itc__mmsystem_h_updated_ 20260624

#include <InterpretConst.h>

namespace itc {

/* Error code ranges, excerpt from mmsystem.h (7 groups)

#define MMSYSERR_BASE          0
#define WAVERR_BASE            32
#define MIDIERR_BASE           64
#define TIMERR_BASE            96
#define JOYERR_BASE            160
#define MCIERR_BASE            256
#define MIXERR_BASE            1024

*/

extern const CInterpretConst& MmsystemError(); // this contains all 7 groups, prefer to use it
//
extern const CInterpretConst& MMSYSERR_xxx();
extern const CInterpretConst& WAVERR_xxx();
extern const CInterpretConst& MIDIERR_xxx();
extern const CInterpretConst& TIMERR_xxx();
extern const CInterpretConst& JOYERR_xxx();
extern const CInterpretConst& MCIERR_xxx();
extern const CInterpretConst& MIXERR_xxx();

extern const CInterpretConst& MCI_NOTIFY_xxx();


} // namespace itc


/*
////////////////////////////////////////////////////////////////////////////
 ___                 _                           _        _   _             
|_ _|_ __ ___  _ __ | | ___ _ __ ___   ___ _ __ | |_ __ _| |_(_) ___  _ __  
 | || '_ ` _ \| '_ \| |/ _ \ '_ ` _ \ / _ \ '_ \| __/ _` | __| |/ _ \| '_ \ 
 | || | | | | | |_) | |  __/ | | | | |  __/ | | | || (_| | |_| | (_) | | | |
|___|_| |_| |_| .__/|_|\___|_| |_| |_|\___|_| |_|\__\__,_|\__|_|\___/|_| |_|
              |_|                                                           
////////////////////////////////////////////////////////////////////////////
*/
// ++++++++++++++++++ Implementation Below ++++++++++++++++++
//
#if defined(mmsystem_itc_IMPL) || (defined CHHI_ALL_IMPL && !defined CHHI_ALL_IMPL_HIDE_mmsystem_itc) // [IMPL] begin
// [IMPL] //
// [IMPL] //
// Include system/OS headers here
#include <mmsystem.h>
// [IMPL] //
// [IMPL] //
namespace itc {

// More ctor reference: My evclip 20250411.v1

const Enum2Val_st _e2v_MMSYSERR_xxx[] =
{
	ITC_NAMEPAIR(MMSYSERR_ERROR       ), // (MMSYSERR_BASE + 1) 
	ITC_NAMEPAIR(MMSYSERR_BADDEVICEID ), // (MMSYSERR_BASE + 2) 
	ITC_NAMEPAIR(MMSYSERR_NOTENABLED  ), // (MMSYSERR_BASE + 3) 
	ITC_NAMEPAIR(MMSYSERR_ALLOCATED   ), // (MMSYSERR_BASE + 4) 
	ITC_NAMEPAIR(MMSYSERR_INVALHANDLE ), // (MMSYSERR_BASE + 5) 
	ITC_NAMEPAIR(MMSYSERR_NODRIVER    ), // (MMSYSERR_BASE + 6) 
	ITC_NAMEPAIR(MMSYSERR_NOMEM       ), // (MMSYSERR_BASE + 7) 
	ITC_NAMEPAIR(MMSYSERR_NOTSUPPORTED), // (MMSYSERR_BASE + 8) 
	ITC_NAMEPAIR(MMSYSERR_BADERRNUM   ), // (MMSYSERR_BASE + 9) 
	ITC_NAMEPAIR(MMSYSERR_INVALFLAG   ), // (MMSYSERR_BASE + 10)
	ITC_NAMEPAIR(MMSYSERR_INVALPARAM  ), // (MMSYSERR_BASE + 11)
	ITC_NAMEPAIR(MMSYSERR_HANDLEBUSY  ), // (MMSYSERR_BASE + 12)
	ITC_NAMEPAIR(MMSYSERR_INVALIDALIAS), // (MMSYSERR_BASE + 13)
	ITC_NAMEPAIR(MMSYSERR_BADDB       ), // (MMSYSERR_BASE + 14)
	ITC_NAMEPAIR(MMSYSERR_KEYNOTFOUND ), // (MMSYSERR_BASE + 15)
	ITC_NAMEPAIR(MMSYSERR_READERROR   ), // (MMSYSERR_BASE + 16)
	ITC_NAMEPAIR(MMSYSERR_WRITEERROR  ), // (MMSYSERR_BASE + 17)
	ITC_NAMEPAIR(MMSYSERR_DELETEERROR ), // (MMSYSERR_BASE + 18)
	ITC_NAMEPAIR(MMSYSERR_VALNOTFOUND ), // (MMSYSERR_BASE + 19)
	ITC_NAMEPAIR(MMSYSERR_NODRIVERCB  ), // (MMSYSERR_BASE + 20)
	ITC_NAMEPAIR(MMSYSERR_MOREDATA    ), // (MMSYSERR_BASE + 21)
	ITC_NAMEPAIR(MMSYSERR_LASTERROR   ), // (MMSYSERR_BASE + 21)
};
ITC_MAKE_OBJECT(MMSYSERR_xxx, _e2v_MMSYSERR_xxx, ITCF_SINT)


const Enum2Val_st _e2v_WAVERR_xxx[] =
{
	ITC_NAMEPAIR(WAVERR_BADFORMAT   ), //  (WAVERR_BASE + 0)
	ITC_NAMEPAIR(WAVERR_STILLPLAYING), //  (WAVERR_BASE + 1)
	ITC_NAMEPAIR(WAVERR_UNPREPARED  ), //  (WAVERR_BASE + 2)
	ITC_NAMEPAIR(WAVERR_SYNC        ), //  (WAVERR_BASE + 3)
	ITC_NAMEPAIR(WAVERR_LASTERROR   ), //  (WAVERR_BASE + 3)
};
ITC_MAKE_OBJECT(WAVERR_xxx, _e2v_WAVERR_xxx, ITCF_SINT)


const Enum2Val_st _e2v_MIDIERR_xxx[] =
{
	ITC_NAMEPAIR(MIDIERR_UNPREPARED   ), // (MIDIERR_BASE + 0)
	ITC_NAMEPAIR(MIDIERR_STILLPLAYING ), // (MIDIERR_BASE + 1)
	ITC_NAMEPAIR(MIDIERR_NOMAP        ), // (MIDIERR_BASE + 2)
	ITC_NAMEPAIR(MIDIERR_NOTREADY     ), // (MIDIERR_BASE + 3)
	ITC_NAMEPAIR(MIDIERR_NODEVICE     ), // (MIDIERR_BASE + 4)
	ITC_NAMEPAIR(MIDIERR_INVALIDSETUP ), // (MIDIERR_BASE + 5)
	ITC_NAMEPAIR(MIDIERR_BADOPENMODE  ), // (MIDIERR_BASE + 6)
	ITC_NAMEPAIR(MIDIERR_DONT_CONTINUE), // (MIDIERR_BASE + 7)
	ITC_NAMEPAIR(MIDIERR_LASTERROR    ), // (MIDIERR_BASE + 7)
};
ITC_MAKE_OBJECT(MIDIERR_xxx, _e2v_MIDIERR_xxx, ITCF_SINT)


const Enum2Val_st _e2v_TIMERR_xxx[] =
{
	ITC_NAMEPAIR(TIMERR_NOERROR ), //       (0)             
	ITC_NAMEPAIR(TIMERR_NOCANDO ), //       (TIMERR_BASE+1) 
	ITC_NAMEPAIR(TIMERR_STRUCT  ), //       (TIMERR_BASE+33)
};
ITC_MAKE_OBJECT(TIMERR_xxx, _e2v_TIMERR_xxx, ITCF_SINT)


const Enum2Val_st _e2v_JOYERR_xxx[] =
{
	ITC_NAMEPAIR(JOYERR_NOERROR  ), //     (0)             
	ITC_NAMEPAIR(JOYERR_PARMS    ), //     (JOYERR_BASE+5) 
	ITC_NAMEPAIR(JOYERR_NOCANDO  ), //     (JOYERR_BASE+6) 
	ITC_NAMEPAIR(JOYERR_UNPLUGGED), //     (JOYERR_BASE+7) 
};
ITC_MAKE_OBJECT(JOYERR_xxx, _e2v_JOYERR_xxx, ITCF_SINT)


const Enum2Val_st _e2v_MCIERR_xxx[] =
{
	ITC_NAMEPAIR(MCIERR_INVALID_DEVICE_ID        ), // (MCIERR_BASE + 1)
	ITC_NAMEPAIR(MCIERR_UNRECOGNIZED_KEYWORD     ), // (MCIERR_BASE + 3)
	ITC_NAMEPAIR(MCIERR_UNRECOGNIZED_COMMAND     ), // (MCIERR_BASE + 5)
	ITC_NAMEPAIR(MCIERR_HARDWARE                 ), // (MCIERR_BASE + 6)
	ITC_NAMEPAIR(MCIERR_INVALID_DEVICE_NAME      ), // (MCIERR_BASE + 7)
	ITC_NAMEPAIR(MCIERR_OUT_OF_MEMORY            ), // (MCIERR_BASE + 8)
	ITC_NAMEPAIR(MCIERR_DEVICE_OPEN              ), // (MCIERR_BASE + 9)
	ITC_NAMEPAIR(MCIERR_CANNOT_LOAD_DRIVER       ), // (MCIERR_BASE + 10)
	ITC_NAMEPAIR(MCIERR_MISSING_COMMAND_STRING   ), // (MCIERR_BASE + 11)
	ITC_NAMEPAIR(MCIERR_PARAM_OVERFLOW           ), // (MCIERR_BASE + 12)
	ITC_NAMEPAIR(MCIERR_MISSING_STRING_ARGUMENT  ), // (MCIERR_BASE + 13)
	ITC_NAMEPAIR(MCIERR_BAD_INTEGER              ), // (MCIERR_BASE + 14)
	ITC_NAMEPAIR(MCIERR_PARSER_INTERNAL          ), // (MCIERR_BASE + 15)
	ITC_NAMEPAIR(MCIERR_DRIVER_INTERNAL          ), // (MCIERR_BASE + 16)
	ITC_NAMEPAIR(MCIERR_MISSING_PARAMETER        ), // (MCIERR_BASE + 17)
	ITC_NAMEPAIR(MCIERR_UNSUPPORTED_FUNCTION     ), // (MCIERR_BASE + 18)
	ITC_NAMEPAIR(MCIERR_FILE_NOT_FOUND           ), // (MCIERR_BASE + 19)
	ITC_NAMEPAIR(MCIERR_DEVICE_NOT_READY         ), // (MCIERR_BASE + 20)
	ITC_NAMEPAIR(MCIERR_INTERNAL                 ), // (MCIERR_BASE + 21)
	ITC_NAMEPAIR(MCIERR_DRIVER                   ), // (MCIERR_BASE + 22)
	ITC_NAMEPAIR(MCIERR_CANNOT_USE_ALL           ), // (MCIERR_BASE + 23)
	ITC_NAMEPAIR(MCIERR_MULTIPLE                 ), // (MCIERR_BASE + 24)
	ITC_NAMEPAIR(MCIERR_EXTENSION_NOT_FOUND      ), // (MCIERR_BASE + 25)
	ITC_NAMEPAIR(MCIERR_OUTOFRANGE               ), // (MCIERR_BASE + 26)
	ITC_NAMEPAIR(MCIERR_FLAGS_NOT_COMPATIBLE     ), // (MCIERR_BASE + 28)
	ITC_NAMEPAIR(MCIERR_FILE_NOT_SAVED           ), // (MCIERR_BASE + 30)
	ITC_NAMEPAIR(MCIERR_DEVICE_TYPE_REQUIRED     ), // (MCIERR_BASE + 31)
	ITC_NAMEPAIR(MCIERR_DEVICE_LOCKED            ), // (MCIERR_BASE + 32)
	ITC_NAMEPAIR(MCIERR_DUPLICATE_ALIAS          ), // (MCIERR_BASE + 33)
	ITC_NAMEPAIR(MCIERR_BAD_CONSTANT             ), // (MCIERR_BASE + 34)
	ITC_NAMEPAIR(MCIERR_MUST_USE_SHAREABLE       ), // (MCIERR_BASE + 35)
	ITC_NAMEPAIR(MCIERR_MISSING_DEVICE_NAME      ), // (MCIERR_BASE + 36)
	ITC_NAMEPAIR(MCIERR_BAD_TIME_FORMAT          ), // (MCIERR_BASE + 37)
	ITC_NAMEPAIR(MCIERR_NO_CLOSING_QUOTE         ), // (MCIERR_BASE + 38)
	ITC_NAMEPAIR(MCIERR_DUPLICATE_FLAGS          ), // (MCIERR_BASE + 39)
	ITC_NAMEPAIR(MCIERR_INVALID_FILE             ), // (MCIERR_BASE + 40)
	ITC_NAMEPAIR(MCIERR_NULL_PARAMETER_BLOCK     ), // (MCIERR_BASE + 41)
	ITC_NAMEPAIR(MCIERR_UNNAMED_RESOURCE         ), // (MCIERR_BASE + 42)
	ITC_NAMEPAIR(MCIERR_NEW_REQUIRES_ALIAS       ), // (MCIERR_BASE + 43)
	ITC_NAMEPAIR(MCIERR_NOTIFY_ON_AUTO_OPEN      ), // (MCIERR_BASE + 44)
	ITC_NAMEPAIR(MCIERR_NO_ELEMENT_ALLOWED       ), // (MCIERR_BASE + 45)
	ITC_NAMEPAIR(MCIERR_NONAPPLICABLE_FUNCTION   ), // (MCIERR_BASE + 46)
	ITC_NAMEPAIR(MCIERR_ILLEGAL_FOR_AUTO_OPEN    ), // (MCIERR_BASE + 47)
	ITC_NAMEPAIR(MCIERR_FILENAME_REQUIRED        ), // (MCIERR_BASE + 48)
	ITC_NAMEPAIR(MCIERR_EXTRA_CHARACTERS         ), // (MCIERR_BASE + 49)
	ITC_NAMEPAIR(MCIERR_DEVICE_NOT_INSTALLED     ), // (MCIERR_BASE + 50)
	ITC_NAMEPAIR(MCIERR_GET_CD                   ), // (MCIERR_BASE + 51)
	ITC_NAMEPAIR(MCIERR_SET_CD                   ), // (MCIERR_BASE + 52)
	ITC_NAMEPAIR(MCIERR_SET_DRIVE                ), // (MCIERR_BASE + 53)
	ITC_NAMEPAIR(MCIERR_DEVICE_LENGTH            ), // (MCIERR_BASE + 54)
	ITC_NAMEPAIR(MCIERR_DEVICE_ORD_LENGTH        ), // (MCIERR_BASE + 55)
	ITC_NAMEPAIR(MCIERR_NO_INTEGER               ), // (MCIERR_BASE + 56)
	
	ITC_NAMEPAIR(MCIERR_WAVE_OUTPUTSINUSE        ), // (MCIERR_BASE + 64)
	ITC_NAMEPAIR(MCIERR_WAVE_SETOUTPUTINUSE      ), // (MCIERR_BASE + 65)
	ITC_NAMEPAIR(MCIERR_WAVE_INPUTSINUSE         ), // (MCIERR_BASE + 66)
	ITC_NAMEPAIR(MCIERR_WAVE_SETINPUTINUSE       ), // (MCIERR_BASE + 67)
	ITC_NAMEPAIR(MCIERR_WAVE_OUTPUTUNSPECIFIED   ), // (MCIERR_BASE + 68)
	ITC_NAMEPAIR(MCIERR_WAVE_INPUTUNSPECIFIED    ), // (MCIERR_BASE + 69)
	ITC_NAMEPAIR(MCIERR_WAVE_OUTPUTSUNSUITABLE   ), // (MCIERR_BASE + 70)
	ITC_NAMEPAIR(MCIERR_WAVE_SETOUTPUTUNSUITABLE ), // (MCIERR_BASE + 71)
	ITC_NAMEPAIR(MCIERR_WAVE_INPUTSUNSUITABLE    ), // (MCIERR_BASE + 72)
	ITC_NAMEPAIR(MCIERR_WAVE_SETINPUTUNSUITABLE  ), // (MCIERR_BASE + 73)
	
	ITC_NAMEPAIR(MCIERR_SEQ_DIV_INCOMPATIBLE     ), // (MCIERR_BASE + 80)
	ITC_NAMEPAIR(MCIERR_SEQ_PORT_INUSE           ), // (MCIERR_BASE + 81)
	ITC_NAMEPAIR(MCIERR_SEQ_PORT_NONEXISTENT     ), // (MCIERR_BASE + 82)
	ITC_NAMEPAIR(MCIERR_SEQ_PORT_MAPNODEVICE     ), // (MCIERR_BASE + 83)
	ITC_NAMEPAIR(MCIERR_SEQ_PORT_MISCERROR       ), // (MCIERR_BASE + 84)
	ITC_NAMEPAIR(MCIERR_SEQ_TIMER                ), // (MCIERR_BASE + 85)
	ITC_NAMEPAIR(MCIERR_SEQ_PORTUNSPECIFIED      ), // (MCIERR_BASE + 86)
	ITC_NAMEPAIR(MCIERR_SEQ_NOMIDIPRESENT        ), // (MCIERR_BASE + 87)
	
	ITC_NAMEPAIR(MCIERR_NO_WINDOW                ), // (MCIERR_BASE + 90)
	ITC_NAMEPAIR(MCIERR_CREATEWINDOW             ), // (MCIERR_BASE + 91)
	ITC_NAMEPAIR(MCIERR_FILE_READ                ), // (MCIERR_BASE + 92)
	ITC_NAMEPAIR(MCIERR_FILE_WRITE               ), // (MCIERR_BASE + 93)
	
	ITC_NAMEPAIR(MCIERR_NO_IDENTITY              ), // (MCIERR_BASE + 94)
};
ITC_MAKE_OBJECT(MCIERR_xxx, _e2v_MCIERR_xxx, ITCF_SINT)


const Enum2Val_st _e2v_MIXERR_xxx[] =
{
	ITC_NAMEPAIR(MIXERR_INVALLINE   ), //         (MIXERR_BASE + 0)
	ITC_NAMEPAIR(MIXERR_INVALCONTROL), //         (MIXERR_BASE + 1)
	ITC_NAMEPAIR(MIXERR_INVALVALUE  ), //         (MIXERR_BASE + 2)
	ITC_NAMEPAIR(MIXERR_LASTERROR   ), //         (MIXERR_BASE + 2)
};
ITC_MAKE_OBJECT(MIXERR_xxx, _e2v_MIXERR_xxx, ITCF_SINT)


ITC_MAKE_OBJECT(MmsystemError,
	new Enum2Val_merge(
		_e2v_MMSYSERR_xxx, ARRAYSIZE(_e2v_MMSYSERR_xxx),
		_e2v_WAVERR_xxx, ARRAYSIZE(_e2v_WAVERR_xxx),
		_e2v_MIDIERR_xxx, ARRAYSIZE(_e2v_MIDIERR_xxx),
		_e2v_TIMERR_xxx, ARRAYSIZE(_e2v_TIMERR_xxx),
		_e2v_JOYERR_xxx, ARRAYSIZE(_e2v_JOYERR_xxx),
		_e2v_MCIERR_xxx, ARRAYSIZE(_e2v_MCIERR_xxx),
		_e2v_MIXERR_xxx, ARRAYSIZE(_e2v_MIXERR_xxx),
		nullptr, 0) // this Enum2Val_merge object will not be deleted, by design
	, ITCF_SINT
	)


////////

const Enum2Val_st _e2v_MCI_NOTIFY_xxx[] =
{
	ITC_NAMEPAIR(MCI_NOTIFY_SUCCESSFUL), //           0x0001
	ITC_NAMEPAIR(MCI_NOTIFY_SUPERSEDED), //           0x0002
	ITC_NAMEPAIR(MCI_NOTIFY_ABORTED   ), //           0x0004
	ITC_NAMEPAIR(MCI_NOTIFY_FAILURE   ), //           0x0008
};
ITC_MAKE_OBJECT(MCI_NOTIFY_xxx, _e2v_MCI_NOTIFY_xxx, ITCF_HEX1B)


} // namespace itc
// [IMPL] //
// [IMPL] //
#endif // [IMPL] end


#endif // include once guard
